### ISSUE TITLE
bug: Message Reply context line missing on nextjs

### ISSUE THREAD

**Issue by mezotv** [skyra-project/discord-components#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

On nextjs the connection line for threads and commands is missing the little connection line between the avatar and the bots avatar.

Observed on https://wouldyoubot.gg/

### Steps To Reproduce

1. Use the discord-reply component (for example)
2. Observe if the line shows up or not

### Expected behavior

The connection line shows up 

### Screenshots

How it should look:

![image](https://github.com/user-attachments/assets/df1b84c3-9a06-40fc-b58d-1f387c6b651c)

How it looks:

![image](https://github.com/user-attachments/assets/ab62a8d7-d223-4a88-b151-f9f9f1653652)
![image](https://github.com/user-attachments/assets/b30a3759-03c2-4fc1-82d1-fd8e7833ef6f)

### Additional context

We use the newest alpha version of the package at this time this is 31, we also use next.js 14.3.1.

**Comment by favna** [comment]
the problem is this styling overwriting the styling from the webcomponent: 
![ishare-1724129858](https://github.com/user-attachments/assets/a4cd738d-6ded-4d38-a973-719b9463f0ee)

Which appears to be a TailwindCSS stylesheet:
```css
/*
! tailwindcss v3.4.10 | MIT License | https://tailwindcss.com
*/
*,:after,:before {
    box-sizing: border-box;
    border: 0 solid #e5e7eb;
}
```

While this is actually something that should be addressed through Tailwind, I believe #454 should also fix it.
